name: first-time
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: |
          echo "This is my first time"
          echo "I will continue learning"
